### ISSUE TITLE
Recent upload names

### ISSUE THREAD

**Issue by chasemc** [idbac/maldidb#7]
It seems like the recent uploads are assigned a name that is a ?hash?  but this isn't clear and impossible for someone to know which recent upload corresponds to which hash.

![image](https://user-images.githubusercontent.com/18691127/125367727-534d8980-e33e-11eb-9314-358a39e86a6c.png)

**Comment by chasemc** [comment]
the "5Eu31Q9J" above

**Comment by davidshumway** [comment]
It's just a random string e.g. in the case that a user isn't concerned, at least initially, with where the files are saved.

**Comment by chasemc** [comment]
Problem is it's not clear unless they have clicked "more options" that they can provide those names. 

And to clarify- I think there's a difference between creating a library and someone just uploading to search. 

I would suggest:

libraries are permanent
all "just an upload" are deleted after e.g. 1 month


- for "just uploading to search" 
 - provide a table of recent uploads
   - columns: hash, date/time, number of files, names of first few files..., date upload will be deleted
   - users can click on the hash or whatever to pull up that data
   
- creating a library 
  - user must fill give it a name or choose to add to an existing library

**Comment by davidshumway** [comment]
Seems reasonable
